### ISSUE TITLE
ЛР 7

### ISSUE THREAD

**Issue by zaq007** [alexanderkoleshko/labsCSharp#1]
Переделайте, пожалуйста, без использования свойства Value 
Оно приносит слишком много ошибок

**Comment by alexanderkoleshko** [comment]
Переделал, проверяйте

**Comment by alexanderkoleshko** [comment]
> Переделайте, пожалуйста, без использования свойства Value
> Оно приносит слишком много ошибок

Переделал, проверяйте

**Comment by alexanderkoleshko** [comment]
Как исправлю, дам знать, а как остальные лабы?
